# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d6f084d439f042bd5efcd924bf762667d212c873a9ed0ee9465aa6f41c9ee9d10cc3c0e7553a1eedb210e92f975fc441079e36628fd5614101cc8f4baf42e0f

test:
  secret_key_base: 109935007af2ebef1cd1a51e1c55b03722ba78a8daac3c7e034778d8d640da8ccd8450a59585b723ade2a5476349a7132c06b8c18789b4f438cd8a24f7902332

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
